### ISSUE TITLE
not all examples are built?

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/omegah_examples#2]
@joshia5 It appears that not all of the examples are built.  Likewise, the tests are missing for those examples.  Is there a branch we should merge into this repo that has all of them?

**Comment by joshia5** [comment]
All the examples were built and successfully tested one-by-one or at most a couple at a time. The details of the build and test cases should be in the history of the repo/build-files. Please let me know if you cant find them.

**Comment by cwsmith** [comment]
OK.  Please add them to this list 'examples' list

https://github.com/SCOREC/omegah_examples/blob/15143b034887738efdbdb5a84bc383a664e1be4e/CMakeLists.txt#L32-L37

and then to the set of tests:

https://github.com/SCOREC/omegah_examples/blob/15143b034887738efdbdb5a84bc383a664e1be4e/testing.cmake#L8-L11
